name: build

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

env:
  # https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080
  MAVEN_OPTS: >-
    -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: m2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Compile
      run: ./mvnw clean test-compile -B
    - name: Test
      run: ./mvnw verify -B
    - name: Deploy
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./mvnw deploy -B
